using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Xamarin.Forms;

namespace MpPdfDemoApp
{
	public partial class MainPage : ContentPage
	{
		public MainPage()
		{
			InitializeComponent();

            btnPdf.Clicked += (sender, e) =>
            {
                var pdf = DependencyService.Get<Helper.IPdfMaker>();
                pdf.DrawPdf("This is a first pdf file generated by Maulik Parmar.");
            };
		}
	}
}
